---
title: "Using Variable Clustering to remove redundant variables"
author: "Lebintiti Kobe"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Goal of this section 

To use variable clustering to remove redundant variables from our data . 

## Load the data

```{r}
require(here)
require(tidyverse)
require(skimr)

data <- read.csv(here("data/kaggle_dataset.csv")) %>% as_tibble()

data <- data %>%
  relocate(target)
data

skimr::skim(data)
```

## split the data 

Split data into test and train data , and data we going to use to test our api
```{r}
set.seed(545672)
require(tidymodels)

splits <- rsample::initial_validation_split(data,strata = target)

test_api <- validation(splits)
test <- testing(splits)
train <- training(splits)

test
train
test_api
```

## Create a recipes 

```{r}
recipe_1 <- train %>%
  recipe(target~.)%>%
  step_rm(ID)%>%
  step_mutate(target=as.factor(target))%>%
  step_indicate_na(all_predictors())%>%
  step_mutate_at(all_predictors(),fn=as.numeric)%>%
  step_nzv(all_predictors())%>%
  step_filter_missing(all_predictors(),threshold = 0.3)%>%
  step_YeoJohnson(all_numeric_predictors())%>%
  step_impute_median(all_numeric_predictors())%>%
  step_scale(all_numeric_predictors())

clust_data <- recipe_1 %>% prep() %>% juice() %>% select(-target)
sapply(clust_data,class)
colnames(clust_data)
```

## remove redundant variables (variable clustering)

```{r}
require(ClustOfVar)

hclust_mod <- hclustvar(X.quanti = clust_data %>% as.matrix())

clusters <- ClustOfVar::cutreevar(hclust_mod,k = 50)
clusters$var
cluster <- "cluster50"
variables_to_keep <- list()
for(cluster in names(clusters$var)){
  
  if(is.null(nrow(clusters$var[[cluster]]))){
    keep <-clusters$cluster[clusters$cluster==gsub("\\D+(\\d+)","\\1",cluster)]%>%
        names()
    variables_to_keep[[cluster]] <- keep
  }
  
  
  if(!is.null(nrow(clusters$var[[cluster]]))){
      small <- clusters$var[[cluster]] %>%
        as.data.frame()%>%as_tibble(rownames="variables")%>%
        filter(abs(`squared loading`) < 0.8 )%>%
        pull(variables)
      
      top <- clusters$var[[cluster]] %>%
      as.data.frame() %>%
      as_tibble(rownames="variables")%>%
      filter(abs(`squared loading`)>=0.75)%>%
      dplyr::slice(1)%>%
      pull(variables)
  
      variables_to_keep[[cluster]] <- c(top,small)
      
  } 
  
}
names_keep <- variables_to_keep %>%
  unlist(use.names = F)
names_keep
```

## Update recipe

```{r}
recipe_1 <- train %>%
  recipe(target~.)%>%
  step_rm(ID)%>%
  step_mutate(target=as.factor(target))%>%
  step_indicate_na(all_predictors())%>%
  step_mutate_at(all_predictors(),fn=as.numeric)%>%
  step_nzv(all_predictors())%>%
  step_filter_missing(all_predictors(),threshold = 0.3)%>%
  step_YeoJohnson(all_numeric_predictors())%>%
  step_select(all_of(names_keep),target)%>%
  step_impute_median(all_numeric_predictors())%>%
  step_scale(all_numeric_predictors())
  

clust_data <- recipe_1 %>% prep() %>% juice() %>% select(-target)
colnames(clust_data)
```

```{r}
hclust_mod <- hclustvar(X.quanti = clust_data %>% as.matrix())

clusters <- ClustOfVar::cutreevar(hclust_mod,k = 15)
clusters$var
variables_to_keep <- list()
for(cluster in names(clusters$var)){
  
  if(is.null(nrow(clusters$var[[cluster]]))){
    keep <-clusters$cluster[clusters$cluster==gsub("\\D+(\\d+)","\\1",cluster)]%>%
        names()
    variables_to_keep[[cluster]] <- keep
  }
  
  
  if(!is.null(nrow(clusters$var[[cluster]]))){
      small <- clusters$var[[cluster]] %>%
        as.data.frame()%>%as_tibble(rownames="variables")%>%
        filter(abs(`squared loading`) < 0.8 )%>%
        pull(variables)
      
      top <- clusters$var[[cluster]] %>%
      as.data.frame() %>%
      as_tibble(rownames="variables")%>%
      filter(abs(`squared loading`)>=0.8)%>%
      dplyr::slice(1)%>%
      pull(variables)
  
      variables_to_keep[[cluster]] <- c(top,small)
      
  } 
  
}
names_keep <- variables_to_keep %>%
  unlist(use.names = F)
names_keep
```

## Update recipe

```{r}
recipe_1 <- train %>%
  recipe(target~.)%>%
  step_rm(ID)%>%
  step_mutate(target=as.factor(target))%>%
  step_indicate_na(all_predictors())%>%
  step_mutate_at(all_predictors(),fn=as.numeric)%>%
  step_nzv(all_predictors())%>%
  step_filter_missing(all_predictors(),threshold = 0.3)%>%
  step_YeoJohnson(all_numeric_predictors())%>%
  step_select(all_of(names_keep),target)%>%
  step_impute_median(all_numeric_predictors())%>%
  step_scale(all_numeric_predictors())

clust_data <- recipe_1 %>% prep() %>% juice() %>% select(-target)
colnames(clust_data)
```

```{r}
hclust_mod <- hclustvar(X.quanti = clust_data %>% as.matrix())

clusters <- ClustOfVar::cutreevar(hclust_mod,k = 10)
clusters$var
variables_to_keep <- list()
for(cluster in names(clusters$var)){
  
  if(is.null(nrow(clusters$var[[cluster]]))){
    keep <-clusters$cluster[clusters$cluster==gsub("\\D+(\\d+)","\\1",cluster)]%>%
        names()
    variables_to_keep[[cluster]] <- keep
  }
  
  if(!is.null(nrow(clusters$var[[cluster]]))){
      small <- clusters$var[[cluster]] %>%
        as.data.frame()%>%as_tibble(rownames="variables")%>%
        filter(abs(`squared loading`) < 0.8 )%>%
        pull(variables)
      
      top <- clusters$var[[cluster]] %>%
      as.data.frame() %>%
      as_tibble(rownames="variables")%>%
      filter(abs(`squared loading`)>=0.8)%>%
      dplyr::slice(1)%>%
      pull(variables)
  
      variables_to_keep[[cluster]] <- c(top,small)
      
  } 
  
}
names_keep <- variables_to_keep %>%
  unlist(use.names = F)
names_keep
```

## Update recipe

```{r}
recipe_1 <- train %>%
  recipe(target~.)%>%
  step_rm(ID)%>%
  step_mutate(target=as.factor(target))%>%
  step_indicate_na(all_predictors())%>%
  step_mutate_at(all_predictors(),fn=as.numeric)%>%
  step_nzv(all_predictors())%>%
  step_filter_missing(all_predictors(),threshold = 0.3)%>%
  step_YeoJohnson(all_numeric_predictors())%>%
  step_select(all_of(names_keep),target)%>%
  step_impute_median(all_numeric_predictors())%>%
  step_scale(all_numeric_predictors())

clust_data <- recipe_1 %>% prep() %>% juice() %>% select(-target)
colnames(clust_data)
```

```{r}
hclust_mod <- hclustvar(X.quanti = clust_data %>% as.matrix())
clusters <- ClustOfVar::cutreevar(hclust_mod,k = 10)
clusters$var

clust_data %>% colnames()

cor_mat <- clust_data %>% select(all_of(names_keep)) %>% cor() 

names <- caret::findCorrelation(cor_mat,cutoff = 0.75,names = T)
names
clusters$var

cor_matrx <- cor_mat %>% as_tibble(rownames="features") %>% relocate("features")
cor_matrx %>%
  filter(features %in% names)%>%
  select(where(~any(.>0.7 | .< -0.7)))%>% print(n=50)

clust_data <- clust_data %>%select(-feature_28,-feature_7,-na_ind_feature_38,-feature_78,-feature_77,-na_ind_feature_39)

cor_mat <- clust_data %>% cor()

caret::findCorrelation(cor_mat,cutoff = 0.75,names = T)

names_keep <- c(colnames(clust_data),"target")
names_keep
```

- Clustering is now done . We removed redundant variables 

```{r}
all_selected_features <- c(names_keep)
all_selected_features

train_features <- gsub("na_ind_","",all_selected_features)
train_features

recipe <- train %>%
  select(all_of(train_features))%>%
  recipe(target~.)%>%
  step_mutate(target=as.factor(target))%>%
  step_indicate_na(all_predictors())

all_features <- recipe %>% prep() %>% juice() %>% colnames()
all_features

features_to_remove <- all_features[!all_features%in%all_selected_features] %>%
  as_tibble()
features_to_remove %>% print(n=50)

train_features <- train_features %>% as_tibble()
train_features

write.csv(features_to_remove,"variables_to_remove_clust.csv",row.names = F)
write.csv(train_features,"train_features_clust.csv",row.names = F)
write.csv(all_selected_features,"all_selected_features_clust.csv",row.names = F)
```
